---
# containerd versions are only relevant for docker
containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.6.28': "{{ containerd_package }}=1.6.28-1"
  '1.6.31': "{{ containerd_package }}=1.6.31-1"
  '1.7.13': "{{ containerd_package }}=1.7.13-1"
  'stable': "{{ containerd_package }}"
  'edge': "{{ containerd_package }}"

# https://download.docker.com/linux/ubuntu/
docker_versioned_pkg:
  'latest': docker-ce
  '20.10': docker-ce=5:20.10.24~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  '24.0': docker-ce=5:24.0.9~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  '26.0': docker-ce=5:26.0.2~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  'stable': docker-ce
  'edge': docker-ce

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '20.10': docker-ce-cli=5:20.10.24~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  '24.0': docker-ce-cli=5:24.0.9~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  '26.0': docker-ce-cli=5:26.0.2~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  'stable': docker-ce-cli
  'edge': docker-ce-cli

docker_package_info:
  pkgs:
    - "{{ containerd_versioned_pkg[docker_containerd_version | string] | default(containerd_package) }}"
    - "{{ docker_cli_versioned_pkg[docker_cli_version | string] | default('docker-ce-cli') }}"
    - "{{ docker_versioned_pkg[docker_version | string] | default('docker-ce') }}"

docker_repo_key_info:
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - '{{ docker_ubuntu_repo_repokey }}'

docker_repo_info:
  repos:
    - >
      deb [arch={{ host_architecture }}] {{ docker_ubuntu_repo_base_url }}
      {{ ansible_distribution_release|lower }}
      stable
